ALGO: HS256
COLLECTIONS:
  DATACOLLECTION: userdata
  USERCREDENTIALSCOLLECTION: usercreds
ENV:
  JWTENV: /home/theefault/API/ApiWithFastAPI/userauth/.env
  MONGOENV: /home/theefault/API/ApiWithFastAPI/userauth/mn.env
