ALGO: HS256
COLLECTIONS:
  DATACOLLECTION: userdata
  TEXTDATACOLL: textdata
  USERCREDENTIALSCOLLECTION: usercreds
ENV:
  JWTENV: userauth/.env
  MONGOENV: /home/shantanujaswal/Github/ApiWithFastAPI/userauth/mn.env
MAIL:
  SENDER: shantanujaswal@outlook.com
