import smtplib
# import getpass
import os
from database.pathsetter import setpath
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
def sendMail(password,receiver_mail):    
    HOST = "smtp-mail.outlook.com"
    PORT = 587
    details = setpath.pathset().openyaml()
    SENDER = details["MAIL"]["SENDER"]
    RECEIVER = receiver_mail
    message = MIMEMultipart("alternative")
    message["Subject"] = "**AUTOGENERATED MAIL BY THE SYSTEM**"
    message["From"] = SENDER
    message["To"] = RECEIVER
    message["Cc"] = SENDER
    message["Bcc"] = RECEIVER

    html=""
    file_path = os.path.join(os.path.dirname(__file__),"format.html")
    with open(file_path,"r") as f:
        html = f.read()
    
    to_send = MIMEText(html,'html')
    message.attach(to_send)

    smtp = smtplib.SMTP(HOST,PORT)

    status,response = smtp.ehlo()
    print(f"STATUS :- {status} ||  RESPOSNE :- {response}")

    status, response = smtp.starttls()
    print(f"STATUS :- {status} || RESPONSE :- {response}")

    status,response = smtp.login(SENDER,password)
    print(f"STATUS :- {status} || RESPONSE :- {response}")

    try:
        smtp.sendmail(SENDER,RECEIVER, message.as_string())
    except Exception as e:
        print(f"Error occured : {str(e)}")
    smtp.quit()


    